# Generated by Django 3.1.4 on 2021-03-10 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('currency_conversion_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='getexchangerate',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='base_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='currency_conversion_api.currency'),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='target_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency_conversion_api.currency'),
        ),
    ]
